### ISSUE TITLE
I can build a portofolio type layout for the website 

### ISSUE THREAD

**Issue by Deepankar1484** [Arun100203/Marketplace_demo#2]
it will be really greatfull to help you. i will make a responsive landing page as portofolio. Just assign me the task with the hacktober fest labeled issue. 
Thanks, 
Deepankar Garg

**Comment by Arun100203** [comment]
yeah @Deepankar1484 good to hear this from you

**Comment by Arun100203** [comment]
You just create dummy template, kindly use this repository, create a branch with your name, push your changes, and create a PR, then I will merge that.

Thanks 
Arun

**Comment by Deepankar1484** [comment]
Hello @Arun100203, please label the issue with the hacktoberfest label.

**Comment by Deepankar1484** [comment]
@Arun100203 please label the issue, i have done my work. Then i will set a PR.

**Comment by Deepankar1484** [comment]
@Arun100203 Thanks man, I have just made a PR. Please approve the PR so i can close the issue.

**Comment by Arun100203** [comment]
Hi @Deepankar1484, 

Good work man, It's good to close this issue, Thanks for your help
