### ISSUE TITLE
Changes in the contact page 

### ISSUE THREAD

**Issue by Deepankar1484** [Arun100203/Marketplace_demo#4]
I integrate a Map in the contact page for a better ui and chagne in the Read me for better user interaction.
Please assign me the task with a hacktoberfest labeled issue.

**Comment by Deepankar1484** [comment]
Hey @Arun100203 , 
please assign e the task with hacktoberfest label

**Comment by Arun100203** [comment]
Hi @Deepankar1484, Good to hear you, I assigned you, you can proceed now, did you get badge last.

**Comment by Deepankar1484** [comment]
Hey @Arun100203 , Thanks for asigning task . And the badge is not yet got due to the 7 day review window

**Comment by Arun100203** [comment]
I merged your Changes, kindly close this issue
